### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Grapeiice** [joellliu/SegmentAndComplete#7]
尊敬的作者您好，我在运行python generate_adv_data_coco.py --random命令时，总是会在第24张图片上出现cuda断言错误（coco数据集的第133张图），之后也偶尔会出现错误，请问是什么原因呢？
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "generate_adv_data_coco.py", line 104, in <module>
    x_adv = attacker.generate(x, y=label, patch_height=patch_height, patch_width=patch_width, xmin=xmin, ymin=ymin)
  File "/home/data1/anaconda3/lib/python3.6/site-packages/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/attack/pgd_patch.py", line 93, in generate
    return super().generate(x, y=y, mask=mask)
  File "/home/data1/anaconda3/lib/python3.6/site-packages/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/attack/projected_gradient_descent.py", line 181, in generate
    return self._attack.generate(x=x, y=y, **kwargs)
  File "/home/data1/anaconda3/lib/python3.6/site-packages/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/attack/projected_gradient_descent_numpy.py", line 380, in generate
    self.num_random_init > 0 and i_max_iter == 0,
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/attack/fast_gradient.py", line 472, in _compute
    perturbation = self._compute_perturbation(batch, batch_labels, mask_batch)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/attack/fast_gradient.py", line 370, in _compute_perturbation
    grad = self.estimator.loss_gradient(batch, batch_labels) * (1 - 2 * int(self.targeted))
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/pytorch_faster_rcnn.py", line 293, in loss_gradient
    output = self._model(inputs_t_patch_removed, labels_t)
  File "/home/data1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/vision/torchvision/models/detection/generalized_rcnn.py", line 96, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/data1/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/vision/torchvision/models/detection/rpn.py", line 364, in forward
    objectness, pred_bbox_deltas, labels, regression_targets)
  File "/home/data1/SegmentAndComplete-main/SegmentAndComplete-main/vision/torchvision/models/detection/rpn.py", line 296, in compute_loss
    sampled_pos_inds = torch.where(torch.cat(sampled_pos_inds, dim=0))[0]
RuntimeError: CUDA error: device-side assert triggered

**Comment by joellliu** [comment]
怀疑是torchvision版本问题？

**Comment by Grapeiice** [comment]
> 怀疑是torchvision版本问题？

torch是1.8.1，torchvision是0.9.1，cuda安装了11.0的

**Comment by Grapeiice** [comment]
> > 怀疑是torchvision版本问题？
> 
> torch是1.8.1，torchvision是0.9.1，cuda安装了11.0的

用这个版本跑通了：
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
